Disable symfony build on master

diff --git a/azure/community_job.yml b/azure/community_job.yml
--- a/azure/community_job.yml
+++ b/azure/community_job.yml
@@ -56,20 +56,22 @@ jobs:
         sed -i "s/function_exists('pcntl_fork')/false/" tests/Filesystem/FilesystemTest.php
         php vendor/bin/phpunit
       displayName: 'Test Laravel'
-    - script: |
-        git clone https://github.com/symfony/symfony.git --branch=master --depth=1
-        cd symfony
-        php7.3 /usr/bin/composer install --no-progress
-        export USE_ZEND_ALLOC=0
-        export USE_TRACKED_ALLOC=1
-        export ASAN_OPTIONS=exitcode=139
-        # Close stdin because we hang on some kind of tty test otherwise.
-        php ./phpunit 0<&-
-        if [ $? -gt 128 ]; then
-          exit 1
-        fi
-      displayName: 'Test Symfony'
-      condition: or(succeeded(), failed())
+    # Symfony has complicated custom PHPUnit handling -- we'd at least need an
+    # --ignore-platform-reqs in there, or run the install under a different version.
+    #- script: |
+    #-   git clone https://github.com/symfony/symfony.git --branch=master --depth=1
+    #-   cd symfony
+    #-   php7.3 /usr/bin/composer install --no-progress
+    #-   export USE_ZEND_ALLOC=0
+    #-   export USE_TRACKED_ALLOC=1
+    #-   export ASAN_OPTIONS=exitcode=139
+    #-   # Close stdin because we hang on some kind of tty test otherwise.
+    #-   php ./phpunit 0<&-
+    #-   if [ $? -gt 128 ]; then
+    #-     exit 1
+    #-   fi
+    #- displayName: 'Test Symfony'
+    #- condition: or(succeeded(), failed())
     - script: |
         git clone https://github.com/amphp/amp.git --branch=master --depth=1
         cd amp
