Finalize

diff --git a/azure/community_job.yml b/azure/community_job.yml
--- a/azure/community_job.yml
+++ b/azure/community_job.yml
@@ -3,6 +3,15 @@ parameters:
   configurationParameters: ''
   timeoutInMinutes: 60
 
+# The purpose of the job is to test open-source community projects against an aggressive
+# debug build, that enables assertions, as well as the address and UB sanitizers. However,
+# we are only interested in finding assertion failures, segfaults and sanitizer violations,
+# and don't care about the actual test results, as there will commonly be failures for
+# pre-release versions of PHP.
+#
+# Because exit() in PHP results in an unclean shutdown, test runs are patching phpunit to
+# avoid the exit, which allows us to also check for memory leaks. Otherwise we use
+# USE_TRACKED_ALLOC=1 to avoid reporting of leaks that will be handled by ZMM.
 jobs:
   - job: ${{ parameters.configurationName }}
     timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
@@ -11,6 +20,8 @@ jobs:
     steps:
     - template: apt.yml
     - script: |
+        # Compile a newer version of curl, otherwise there will be an asan warning
+        # when running symfony tests.
         wget https://curl.haxx.se/download/curl-7.65.3.tar.gz
         tar xzf curl-7.65.3.tar.gz
         cd curl-7.65.3/
@@ -29,8 +40,10 @@ jobs:
         sudo chmod 777 /etc/php.d
         echo mysqli.default_socket=/var/run/mysqld/mysqld.sock     > /etc/php.d/mysqli.ini
         echo pdo_mysql.default_socket=/var/run/mysqld/mysqld.sock  > /etc/php.d/pdo_mysql.ini
+        # Run with opcache to also catch optimizer bugs.
         echo zend_extension=opcache.so > /etc/php.d/opcache.ini
         echo opcache.enable_cli=1 >> /etc/php.d/opcache.ini
+        echo opcache.protect_memory=1 >> /etc/php.d/opcache.ini
       displayName: 'Install Build'
     - script: |
         git clone https://github.com/laravel/framework.git --branch=master --depth=1
@@ -50,9 +63,9 @@ jobs:
         export USE_ZEND_ALLOC=0
         export USE_TRACKED_ALLOC=1
         export ASAN_OPTIONS=exitcode=139
-        php ./phpunit --debug 0<&-
-        status=$?
-        if [ $status -gt 128 ]; then
+        # Close stdin because we hang on some kind of tty test otherwise.
+        php ./phpunit 0<&-
+        if [ $? -gt 128 ]; then
           exit 1
         fi
       displayName: 'Test Symfony'
