Upgrade PCRE to version 3.4.
git-svn-id: http://svn.php.net/repository/php/php-src/php/php-src/trunk@41607 c90b9560-bf6c-de11-be94-00142212c4b1

diff --git a/ext/pcre/pcrelib/RunTest b/ext/pcre/pcrelib/RunTest
--- a/ext/pcre/pcrelib/RunTest
+++ b/ext/pcre/pcrelib/RunTest
@@ -1,5 +1,8 @@
 #! /bin/sh
 
+# This file is generated by configure from RunTest.in. Make any changes
+# to that file.
+
 # Run PCRE tests
 
 cf=diff
@@ -10,6 +13,8 @@ do1=no
 do2=no
 do3=no
 do4=no
+do5=no
+do6=no
 
 while [ $# -gt 0 ] ; do
   case $1 in
@@ -17,16 +22,32 @@ while [ $# -gt 0 ] ; do
     2) do2=yes;;
     3) do3=yes;;
     4) do4=yes;;
+    5) do5=yes;; 
+    6) do6=yes;; 
     *) echo "Unknown test number $1"; exit 1;;
   esac
   shift
 done
 
-if [ $do1 = no -a $do2 = no -a $do3 = no -a $do4 = no ] ; then
+if [ "" = "" ] ; then
+  if [ $do5 = yes ] ; then
+    echo "Can't run test 5 because UFT8 support is not configured"
+    exit 1
+  fi   
+  if [ $do6 = yes ] ; then
+    echo "Can't run test 6 because UFT8 support is not configured"
+    exit 1
+  fi   
+fi    
+
+if [ $do1 = no -a $do2 = no -a $do3 = no -a $do4 = no -a\
+     $do5 = no -a $do6 = no ] ; then
   do1=yes
   do2=yes
   do3=yes
   do4=yes
+  if [ "" != "" ] ; then do5=yes; fi
+  if [ "" != "" ] ; then do6=yes; fi
 fi
 
 # Primary test, Perl-compatible
@@ -66,6 +87,7 @@ if [ $do3 = yes ] ; then
 fi
 
 if [ $do1 = yes -a $do2 = yes -a $do3 = yes ] ; then
+  echo " " 
   echo "The three main tests all ran OK"
   echo " " 
 fi
@@ -79,8 +101,14 @@ if [ $do4 = yes ] ; then
     ./pcretest testdata/testinput4 testtry
     if [ $? = 0 ] ; then
       $cf testtry testdata/testoutput4
-      if [ $? != 0 ] ; then exit 1; fi
+      if [ $? != 0 ] ; then 
+        echo " "
+        echo "Locale test did not run entirely successfully."
+        echo "This usually means that there is a problem with the locale"
+        echo "settings rather than a bug in PCRE."    
+      else
       echo "Locale test ran OK" 
+      fi 
       echo " " 
     else exit 1
     fi
@@ -89,6 +117,32 @@ if [ $do4 = yes ] ; then
     echo "or the \"locale\" command is not available to check for it."
     echo " " 
   fi
+fi
+
+# Additional tests for UTF8 support
+
+if [ $do5 = yes ] ; then
+  echo "Testing experimental, incomplete UTF8 support (Perl compatible)"
+  ./pcretest testdata/testinput5 testtry 
+  if [ $? = 0 ] ; then
+    $cf testtry testdata/testoutput5
+    if [ $? != 0 ] ; then exit 1; fi
+  else exit 1
+  fi
+  echo "UTF8 test ran OK"
+  echo " "
+fi
+
+if [ $do6 = yes ] ; then
+  echo "Testing API and internals for UTF8 support (not Perl compatible)"
+  ./pcretest testdata/testinput6 testtry 
+  if [ $? = 0 ] ; then
+    $cf testtry testdata/testoutput6
+    if [ $? != 0 ] ; then exit 1; fi
+  else exit 1
+  fi
+  echo "UTF8 internals test ran OK"
+  echo " "
 fi
 
 # End
