Add versions checking script
This tool checks for the required versions of bison, re2c and possible
more in the future. Having versions on multiple places accross the
repository is error prone and hopefully this might help tackle this
issue a bit.

Move checkings from makedist to genfiles

Add make override in genfiles

diff --git a/scripts/dev/genfiles b/scripts/dev/genfiles
--- a/scripts/dev/genfiles
+++ b/scripts/dev/genfiles
@@ -41,6 +41,9 @@ YACC="$YACC -l"
 RE2C=${RE2C:-re2c}
 RE2C_FLAGS="-i"
 
+# Make
+MAKE=${MAKE:-make}
+
 # Current path to return to it later. This enables running script from any path.
 original_path=`pwd`
 
@@ -48,8 +51,36 @@ original_path=`pwd`
 project_root=`CDPATH= cd -- "$(dirname -- "$0")/../../" && pwd -P`
 cd $project_root
 
+# Check bison version.
+bison_check=$(YACC=$YACC ./build/versions.sh --bison)
+bison_version=$(YACC=$YACC ./build/versions.sh --bison --version)
+bison_min_version=$(YACC=$YACC ./build/versions.sh --bison --min-version)
+case $bison_check in
+  ""|invalid)
+    echo "You will need bison >= $bison_min_version if you want to generate parser files (found $bison_version)." >&2
+    exit 1
+  ;;
+esac
+
+# Check re2c version.
+re2c_check=$(RE2C=$RE2C ./build/versions.sh --re2c)
+re2c_version=$(RE2C=$RE2C ./build/versions.sh --re2c --version)
+re2c_min_version=$(RE2C=$RE2C ./build/versions.sh --re2c --min-version)
+case $re2c_check in
+  ""|invalid)
+    echo "You will need re2c >= $re2c_min_version if you want to generate lexer files (found $re2c_version)." >&2
+    exit 1
+  ;;
+esac
+
+# Check if make exists.
+if ! test -x "$(command -v $MAKE)"; then
+  echo "make not found. Please install make to generate files." >&2
+  exit 1
+fi
+
 echo "Generating Zend parser and lexer files"
-make RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" YACC="$YACC" srcdir=Zend builddir=Zend top_srcdir=. \
+$MAKE RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" YACC="$YACC" srcdir=Zend builddir=Zend top_srcdir=. \
   -f Zend/Makefile.frag \
   Zend/zend_language_parser.c \
   Zend/zend_language_scanner.c \
@@ -57,30 +88,30 @@ make RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" YACC="$YACC" srcdir=Zend builddir=Zen
   Zend/zend_ini_scanner.c
 
 echo "Generating phpdbg parser and lexer files"
-make RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" YACC="$YACC" srcdir=sapi/phpdbg builddir=sapi/phpdbg top_srcdir=. \
+$MAKE RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" YACC="$YACC" srcdir=sapi/phpdbg builddir=sapi/phpdbg top_srcdir=. \
   -f sapi/phpdbg/Makefile.frag \
   sapi/phpdbg/phpdbg_parser.c \
   sapi/phpdbg/phpdbg_lexer.c
 
 echo "Generating json extension parser and lexer files"
-make RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" YACC="$YACC" srcdir=ext/json builddir=ext/json top_srcdir=. \
+$MAKE RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" YACC="$YACC" srcdir=ext/json builddir=ext/json top_srcdir=. \
   -f ext/json/Makefile.frag \
   ext/json/json_parser.tab.c \
   ext/json/json_scanner.c
 
 echo "Generating PDO lexer file"
-make RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" srcdir=ext/pdo builddir=ext/pdo top_srcdir=. \
+$MAKE RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" srcdir=ext/pdo builddir=ext/pdo top_srcdir=. \
   -f ext/pdo/Makefile.frag \
   ext/pdo/pdo_sql_parser.c
 
 echo "Generating standard extension lexer files"
-make RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" srcdir=ext/standard builddir=ext/standard top_srcdir=. \
+$MAKE RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" srcdir=ext/standard builddir=ext/standard top_srcdir=. \
   -f ext/standard/Makefile.frag \
   ext/standard/var_unserializer.c \
   ext/standard/url_scanner_ex.c
 
 echo "Generating phar extension lexer file"
-make RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" srcdir=ext/phar builddir=ext/phar top_srcdir=. \
+$MAKE RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" srcdir=ext/phar builddir=ext/phar top_srcdir=. \
   -f ext/phar/Makefile.frag \
   ext/phar/phar_path_check.c
 
