Refactor PHP_PROG_BISON and PHP_PROG_RE2C
This patch refactors these macros to also checks for the required given
versions of bison and re2c.

- PHP_PROG_RE2C and PHP_PROG_BISON take optional args - minmimum version
  required, and bison also excluded versions.
- Instead of caching values this uses manual checking and messaging
  outputs.
- It looks like the minimum version of RE2C 0.13.4 is working ok so far.

The genfiles script improvements:
- Add make override in genfiles
- Move checkings from makedist to genfiles
- Refactored output messages
- Various minor enhancements

diff --git a/scripts/dev/genfiles b/scripts/dev/genfiles
--- a/scripts/dev/genfiles
+++ b/scripts/dev/genfiles
@@ -29,60 +29,110 @@
 #
 #     YACC    Parser generator program, default bison
 #     RE2C    Lexer generator program, default re2c
+#     SED     Path to sed program, default sed
+#     MAKE    Path to make program, default make
 #
 #   For example:
 #     YACC=/path/to/bison ./genfiles
 
-# Parser generator
 YACC=${YACC:-bison}
 YACC="$YACC -l"
-
-# Lexer generator
 RE2C=${RE2C:-re2c}
 RE2C_FLAGS="-i"
+SED=${SED:-sed}
+MAKE=${MAKE:-make}
 
-# Current path to return to it later. This enables running script from any path.
-original_path=`pwd`
+# Go to project root.
+cd $(CDPATH= cd -- "$(dirname -- "$0")/../../" && pwd -P)
 
-# Project root directory
-project_root=`CDPATH= cd -- "$(dirname -- "$0")/../../" && pwd -P`
-cd $project_root
+# Check required bison version from the configure.ac file.
+required_bison_version=$($SED -n 's/PHP_PROG_BISON(\[\([0-9\.]*\)\].*/\1/p' configure.ac)
+set -f; IFS='.'; set -- $required_bison_version; set +f; IFS=' '
+required_bison_num="$(expr ${1:-0} \* 10000 + ${2:-0} \* 100 + ${3:-0})"
 
-echo "Generating Zend parser and lexer files"
-make RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" YACC="$YACC" srcdir=Zend builddir=Zend top_srcdir=. \
+current_version=$($YACC --version 2> /dev/null | grep 'GNU Bison' | cut -d ' ' -f 4 | tr -d a-z)
+set -f; IFS='.'; set -- $current_version; set +f; IFS=' '
+current_bison_num="$(expr ${1:-0} \* 10000 + ${2:-0} \* 100 + ${3:-0})"
+
+if test -z "$current_version"; then
+  echo "genfiles: bison not found." >&2
+  echo "          You need bison version $required_bison_version or newer installed" >&2
+  echo "          to regenerate parser files." >&2
+  exit 1
+fi
+
+if test "$current_bison_num" -lt "$required_bison_num"; then
+  echo "genfiles: bison version $current_version found." >&2
+  echo "          You need bison version $required_bison_version or newer installed" >&2
+  echo "          to build parser files." >&2
+  exit 1
+else
+  echo "genfiles: bison version $current_version (ok)"
+fi
+
+# Check required re2c version from the configure.ac file.
+required_re2c_version=$($SED -n 's/PHP_PROG_RE2C(\[\(.*\)\])/\1/p' configure.ac)
+set -f; IFS='.'; set -- $required_re2c_version; set +f; IFS=' '
+required_re2c_num="$(expr ${1:-0} \* 10000 + ${2:-0} \* 100 + ${3:-0})"
+
+current_version="$($RE2C --version | cut -d ' ' -f 2  2>/dev/null)"
+set -f; IFS='.'; set -- $current_version; set +f; IFS=' '
+current_re2c_num="$(expr ${1:-0} \* 10000 + ${2:-0} \* 100 + ${3:-0})"
+
+if test -z "$current_version"; then
+  echo "genfiles: re2c not found." >&2
+  echo "          You need re2c version $required_re2c_version or newer installed" >&2
+  echo "          to regenerate lexer files." >&2
+  exit 1
+fi
+
+if test "$current_re2c_num" -lt "$required_re2c_num"; then
+  echo "genfiles: re2c version $current_version found." >&2
+  echo "          You need re2c version $required_re2c_version or newer installed" >&2
+  echo "          to build lexer files." >&2
+  exit 1
+else
+  echo "genfiles: re2c version $current_version (ok)"
+fi
+
+# Check if make exists.
+if ! test -x "$(command -v $MAKE)"; then
+  echo "genfiles: make not found. Please install make to generate files." >&2
+  exit 1
+fi
+
+echo "genfiles: Generating Zend parser and lexer files"
+$MAKE RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" YACC="$YACC" srcdir=Zend builddir=Zend top_srcdir=. \
   -f Zend/Makefile.frag \
   Zend/zend_language_parser.c \
   Zend/zend_language_scanner.c \
   Zend/zend_ini_parser.c \
   Zend/zend_ini_scanner.c
 
-echo "Generating phpdbg parser and lexer files"
-make RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" YACC="$YACC" srcdir=sapi/phpdbg builddir=sapi/phpdbg top_srcdir=. \
+echo "genfiles: Generating phpdbg parser and lexer files"
+$MAKE RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" YACC="$YACC" srcdir=sapi/phpdbg builddir=sapi/phpdbg top_srcdir=. \
   -f sapi/phpdbg/Makefile.frag \
   sapi/phpdbg/phpdbg_parser.c \
   sapi/phpdbg/phpdbg_lexer.c
 
-echo "Generating json extension parser and lexer files"
-make RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" YACC="$YACC" srcdir=ext/json builddir=ext/json top_srcdir=. \
+echo "genfiles: enerating json extension parser and lexer files"
+$MAKE RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" YACC="$YACC" srcdir=ext/json builddir=ext/json top_srcdir=. \
   -f ext/json/Makefile.frag \
   ext/json/json_parser.tab.c \
   ext/json/json_scanner.c
 
-echo "Generating PDO lexer file"
-make RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" srcdir=ext/pdo builddir=ext/pdo top_srcdir=. \
+echo "genfiles: Generating PDO lexer file"
+$MAKE RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" srcdir=ext/pdo builddir=ext/pdo top_srcdir=. \
   -f ext/pdo/Makefile.frag \
   ext/pdo/pdo_sql_parser.c
 
-echo "Generating standard extension lexer files"
-make RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" srcdir=ext/standard builddir=ext/standard top_srcdir=. \
+echo "genfiles: Generating standard extension lexer files"
+$MAKE RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" srcdir=ext/standard builddir=ext/standard top_srcdir=. \
   -f ext/standard/Makefile.frag \
   ext/standard/var_unserializer.c \
   ext/standard/url_scanner_ex.c
 
-echo "Generating phar extension lexer file"
-make RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" srcdir=ext/phar builddir=ext/phar top_srcdir=. \
+echo "genfiles: Generating phar extension lexer file"
+$MAKE RE2C="$RE2C" RE2C_FLAGS="$RE2C_FLAGS" srcdir=ext/phar builddir=ext/phar top_srcdir=. \
   -f ext/phar/Makefile.frag \
   ext/phar/phar_path_check.c
-
-# Return to the original directory.
-cd $original_path
